### PR TITLE
doc: Add IPlotter example

### PR DESCRIPTION
**Pull request by JaviMerino**

### CODE REVIEW

**Comment by sinkap** [comment]
Would be nice to run this notebook through publish_interactive_plots.py so that the plots are globally accessible.

**Comment by JaviMerino** [comment]
Sure, can you do it?  We will have to export it as HTML if we want the world to be able to see it from github itself.

**Comment by sinkap** [comment]
I have created a pull request #16 for this.

**Comment by JaviMerino** [comment]
Ok, so this can be closed as we won't merge it, no?

**Comment by sinkap** [comment]
Yes, this can be closed.

**Pull request closed without merging**
