### PR TITLE
trappy: Add a line number column

### PR DESCRIPTION
**Pull request by joelagnel**
Useful for joining DataFrames that have timestamp collisions or for iterating
through a group of DataFrames in line order.

Signed-off-by: Joel Fernandes <joelaf@google.com>

### CODE REVIEW

**Comment by joelagnel** [comment]
CC @bjackman @sinkap @derkling @bjackman @JaviMerino

**Comment by bjackman** [comment]
Looks good to me :+1:

**Comment by sinkap** [comment]
I will test this and the other PRs today and merge these.

**Comment by joelagnel** [comment]
Hi Patrick,
I will add the systrace test.
Also about storing of exact position in trace file (file offset) will need yet another column because in systrace there is an offset between start of the trace and start of the trace file. I think for now it's ok to just use exact event position from start of the trace and a future patch can store an "offset" field in the FTrace object. Will refresh this PR shortly and then @sinkap can further review, thanks.

**Comment by derkling** [comment]
@joelagnel  the implementation I've provided in here:
https://github.com/ARM-software/lisa/pulls
should already skip everything is not a trace event, i.e. the first trace event will get ID=0.

This is done using a feature already there in trappy which allows to skip non trace event lines... have a try, I think it should work for systrace as well. Meaning the first systrace event you have should get ID=0.

**Comment by joelagnel** [comment]
Hi @derkling yes what I meant is I will use those commits from your PR which do what you wanted, thanks.

**Comment by sinkap** [comment]
merged.

**Pull request closed without merging**
