### PR TITLE
parse traces from ext4 events

### PR DESCRIPTION
**Pull request by kdub**
Adds trace parsing for ext4_da_write_begin, ext4_da_write_end,
ext4_sync_file_enter, and ext4_sync_file_exit events

Test: run the 4 new unit tests (nosetests tests/test_filesystem.py)
Change-Id: I9b7049d5e9879cc3dedb5fd9d3d1433fa8304618

### CODE REVIEW

**Comment by bjackman** [comment]
Thanks for the contributions! Will review the other one next week.

**Comment by kdub** [comment]
thanks for review, adopted changes

**Comment by bjackman** [comment]
Ah, looks like the 2 PRs conflicted with each other. Could you rebase this onto master?

**Comment by kdub** [comment]
Sure, rebased, waiting for travis CI to complete

**Pull request merged**
