### PR TITLE
ILineplot embed data

### PR DESCRIPTION
**Pull request by JaviMerino**
The missing piece to get notebooks that can be exported to HTML

### CODE REVIEW

**Comment by mdigiorgio** [comment]
Sweeeet :+1:

**Comment by sinkap** [comment]
Will try this today and merge it. From a change perspective it looks good to me.

**Comment by derkling** [comment]
Testing it now using this LISA tutorial notebook:
   https://github.com/ARM-software/lisa/blob/master/ipynb/tutorial/UseCaseExamples_SchedTuneAnalysis.ipynb
and I've got that error:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-18-6e115c5ffcf9> in <module>()
     26 
     27     sync_zoom=True,
---> 28     group="GroupTag"
     29 
     30 ).view()

/home/derkling/Code/lisa/libs/trappy/trappy/plotter/ILinePlot.py in view(self, test)
    163             self._plot_concat()
    164         else:
--> 165             self._plot(self._attr["permute"], test)
    166 
    167     def set_defaults(self):

/home/derkling/Code/lisa/libs/trappy/trappy/plotter/ILinePlot.py in _plot(self, permute, test)
    211 
    212             # Fix data frame indexes if necessary
--> 213             data_dict = self._fix_indexes(data_dict)
    214             self._layout.add_plot(plot_index, data_dict, title, test=test)
    215             plot_index += 1

/home/derkling/Code/lisa/libs/trappy/trappy/plotter/ILinePlot.py in _fix_indexes(self, data_dict)
    272             return merged_df
    273         else:
--> 274             return ret

UnboundLocalError: local variable 'ret' referenced before assignment
```

The code which generate the error is:
```python
# Signals can be easily plot using the ILinePlotter
trappy.ILinePlot(
    
    # FTrace object
    trace.ftrace,
    
    # Signals to be plotted
    signals=[
      'cpu_capacity:capacity',
      'sched_load_avg_task:util_avg'
    ],
    
    # Generate one plot for each value of the specified column
     pivot='cpu',
    
    # Generate only plots which satisfy these filters
    filters={
        'comm': ['task_ramp'],
        'cpu' : [2,5]
    },
    
    # Formatting style
    per_line=2,
    drawstyle='steps-post',
    marker = '+',
    
    sync_zoom=True,
    group="GroupTag"

).view()
```

**Comment by mdigiorgio** [comment]
Just need to change the last line of `_fix_indexes` to:

```python
ret data_dict
```

**Comment by JaviMerino** [comment]
Argh, my bad, I'll send a v2

**Comment by sinkap** [comment]
merged in #187

**Pull request closed without merging**
