### PR TITLE
Constraint fixes

### PR DESCRIPTION
**Pull request by JaviMerino**
A number of simplifications of the Constraint code.  The most important is the first one that fixes a bug for which with some traces we raise a "Unable to handle duplicates" where we shouldn't.

### CODE REVIEW

**Comment by JaviMerino** [comment]
@deggeman The first patch should fix your problem regarding plots with multiple filters that were failing with "Unable to handle duplicates".  Can you please test it?

**Comment by deggeman** [comment]
Tested on a ipynb which uses lots of filters with multiple entries in trappy.ILinePlot(..., filters = { ... }, ...). No problems encountered :-)
(It was failing before and the only workaround was to lower max_delta in handle_duplicate_index()?)

**Comment by sinkap** [comment]
Only one comment about handle_duplicate_indices. Otherwise, if @deggeman is happy, so am I :smile:

**Comment by JaviMerino** [comment]
Merged as #146

**Pull request closed without merging**
